### ISSUE TITLE
EPIC 02 - Setup API/V1 Controllers

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread_be#14]
- [x] I[temsController](https://github.com/zachholcomb/good_bread_be/projects/2#card-44789151)
- [x] [UsersController](https://github.com/zachholcomb/good_bread_be/projects/2#card-44789144)
- [x] [SubscriptionsController](https://github.com/zachholcomb/good_bread_be/projects/2#card-44789157)
- [x] [ShipmentsController](https://github.com/zachholcomb/good_bread_be/projects/2#card-44789167)
