### ISSUE TITLE
EPIC 04 - User Roles

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread_be#26]
- [ ] Set up user enums
- [ ] Set up user restrictions
- [ ] Namespace all admin routes
- [ ] Add admin check to all controllers
