### ISSUE TITLE
User Access

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread_be#29]
- [x] User has access to show and index for items
- [x] User has access to subscription crud
- [x] User has access to shipment crud except destroy and update
